spring.application.name=generate-document
springfox.documentation.swagger.v2.path=/api-docs

spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Server
server.port=8400
server.servlet.context-path=/enterprise/workforceManagement/v1

#Configuraciones MongoDb
spring.data.mongodb.uri=mongodb://svc-wfm-mongo.claro-wfm.svc:27017/generate-document
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

#externalizacion de config log
logging.config=/config/log4j2.xml