spring.application.name=generate-document

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force-response=true

# Server
server.port=8400
server.servlet.context-path=/enterprise/m2m-autogestion/v2
server.undertow.max-http-post-size = -1
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
#Configuraciones Oracle

# HikariCP settings
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=20
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.schema=VOUCHER_BL
spring.datasource.hikari.poolName=${spring.application.name}-pool

# SECRETS
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.url=jdbc:oracle:thin:@//${DB_HOST:10.38.56.213:1521}/${DB_SERVICE_NAME:PDBFINAN27.netdesabasesdat.vcndesabasesdat.oraclevcn.com}
spring.datasource.username=${USER_DB:voucher}
spring.datasource.password=${PASSWORD_DB:6J$TGN2ns5t5}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

logging.level.org.springframework.data.jdbc.core=DEBUG

#externalizacion de config log
logging.config=C:/Gizlo/Claro/document-manager/generate-document/log4j2.xml

#swagger
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER


#CONFIGURACION ACTUATOR

management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always
