spring.application.name=generate-document

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force-response=true

# Server
server.port=8400
server.servlet.context-path=/enterprise/m2m-autogestion/v2
server.undertow.max-http-post-size=-1
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Configuracion del pool de conexiones HikariCP
spring.datasource.hikari.dataSourceProperties.fastConnectionFailoverEnabled=true


# HikariCP settings
# spring.datasource.hikari.*

spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idleTimeout=600000
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.minimum-idle=2
#spring.datasource.hikari.pool-name=${spring.application.name}-pool
# DEV
#spring.datasource.hikari.schema=VOUCHER_BL
# PROD
spring.datasource.hikari.schema=OPS$INVENTAR

# SECRETS
#DEV
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
#spring.datasource.url=jdbc:oracle:thin:@//10.38.56.213:1521/PDBFINAN27.netdesabasesdat.vcndesabasesdat.oraclevcn.com
#spring.datasource.username=voucher
#PROD
spring.datasource.url=jdbc:oracle:thin:@//10.31.32.28:8766/GYE
spring.datasource.username=APPORTFINANC
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

#externalizacion de config log
logging.config=C:/Users/GIZLO036/Desktop/CLARO/gitlab-claro/generate-document/log4j2.xml

#swagger
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER


#CONFIGURACION ACTUATOR
management.endpoints.web.exposure.include=*
management.endpoint.metrics.enabled=true
management.endpoint.health.show-details=always


logging.level.cn.afterturn.easypoi.util.*=OFF